
all: small_synthDF stabilityDF015

###############################################################################

small_synthDF: synthDF
	python makefile_small.py

stabilityDF015: synthDF
	python makefile_stability.py
